lead/urls.py
# URLConfiguration
#
# by Sean 2019.03



from django.urls import path, register_converter

from .views import (
	PostListView,
	PostDetailView,
	#LeadCreateView,
	leadcreate
  )

app_name = 'lead'

urlpatterns = [
    # path('', views.coming_soon_render, name='index'),
	# path('aboutus/', FormView.as_view(), name='aboutus'),
	# path('keepgrow/', FormView.as_view(), name='keepgrow')
	
    #path('form/submitted/',Form  name='formsubmit')
    path('form/', leadcreate, name='form'),
    path('posts/', PostListView.as_view(), name='postlist'),
    path('post/<int:id>/', PostDetailView.as_view(), name='postdetail'),
]

lead/models.py
#-*-coding: utf-8

from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings # import to call user object
from django.urls import reverse
from django.utils.text import slugify

from django.utils.safestring import mark_safe

# Validation Area
from django import forms
def clean_corporation(value):
    if any(form_input in value for form_input in ('(주)', '주식회사','Inc.','Ltd.','ltd.','Co.')):
        raise forms.ValidationError(" \"(주)\", \"주식회사\", \"Ltd\"등을 제외한 순수 법인명을 입력해 주세요")

def clean_company(value):
    # ORM => Validation 만약 컴퍼니가 있는지?
    if any(form_input in value for form_input in ('(주)', '주식회사','Inc.','Ltd.','ltd.','Co.')):
        raise forms.ValidationError(" \"(주)\", \"주식회사\", \"Ltd\"등을 제외한 순수 업체명을 입력해 주세요")

def clean_website_url(value):
    if 'http' not in value:
        raise forms.ValidationError("\"http://\" 혹은 \"https://\" 를 입력해 주세요.")

#def agreement(value):
#    if not value:
#        raise forms.ValidationError("수신")

class Lead(models.Model):
    class Meta:
        verbose_name			= 'Lead'
        verbose_name_plural		= 'Leads'
        ordering				= ['-id']

    lead_company_corporation = models.CharField('법인명', null=True, blank=True, max_length=50, validators=[clean_corporation])
    lead_company_name = models.CharField('업체명', null=True, blank=True, max_length=50, validators=[clean_company])
    lead_company_website_url = models.CharField('웹사이트 주소', null=True, blank=True, max_length=200, validators=[clean_website_url])

    lead_contact_department = models.CharField('부서명', null=True, blank=True, max_length=50,)
    lead_contact_name = models.CharField('이름', null=False, blank=False, max_length=50,)
    lead_contact_title = models.CharField('직책', null=True, blank=True, max_length=50,)
    lead_contact_email = models.EmailField('Email', null=False, blank=False,)
    lead_contact_phone = models.CharField('휴대전화', null=True, blank=True, max_length=50,)

    lead_event_interests = models.CharField('관심서비스', null=True, blank=True, max_length=100,)
    lead_event_inquiry = models.TextField('상세 문의사항', null=True, blank=True,)
    lead_event_referrer = models.CharField('리퍼러', null=True, blank=True, max_length=600,)
    lead_event_location = models.CharField('제출 위치', null=True, blank=True, max_length=600,)
    lead_event_location_title = models.CharField('제출 위치 제목', null=True, blank=True, max_length=100,)
    lead_event_submitted_at = models.DateTimeField('제출일', null=True, blank=True, auto_now_add=True,)
    lead_event_user_agent = models.CharField('User_Agent', null=False, blank=False, max_length=400,)
    # IP4 & IP6 모두 호환
    lead_event_ipaddress = models.GenericIPAddressField('IP Address', null=False, blank=False, protocol='both')
	
    lead_marketing_agree = models.BooleanField('마케팅 수신동의', default=False)
    lead_demo_request = models.BooleanField('데모 요청', default=False)
    def __str__(self):
        return f'{self.lead_company_name} - {self.lead_contact_name} {self.lead_contact_title}' 


class Subscription(models.Model):
    class Meta:
        verbose_name			= 'Subscription'
        verbose_name_plural		= 'Subscriptions'
        ordering				= ['-id']

    subs_corporation = models.CharField('법인명', null=True, blank=True, max_length=50,)
    subs_company = models.CharField('업체명', null=False, blank=False, max_length=50,)
    subs_department = models.CharField('부서명', null=True, blank=True, max_length=50,)
    subs_name = models.CharField('이름', null=False, blank=False, max_length=50,)
    subs_title = models.CharField('직책', null=True, blank=True, max_length=50,)
    subs_email = models.EmailField('Email', null=False, blank=False,)
    subs_phone = models.CharField('휴대전화', null=True, blank=True, max_length=50,)
    subs_interests = models.CharField('관심서비스', null=True, blank=True, max_length=100,)
    subs_inquiry = models.TextField('상세 문의사항', null=True, blank=True,)
    subs_referrer = models.CharField('리퍼러', null=True, blank=True, max_length=300,)
    subs_location = models.CharField('제출 위치', null=True, blank=True, max_length=300,)
    subs_location_title = models.CharField('제출 위치 제목', null=True, blank=True, max_length=100,)
    subs_submitted_at = models.DateTimeField('제출일', null=True, blank=True, auto_now_add=True,)
    # IP4 & IP6 모두 호환
    subs_ipaddress = models.GenericIPAddressField('IP Address', null=False, blank=False, protocol='both')

    def __str__(self):
        return f'{self.subs_company} - {self.subs_name} {self.subs_title}'

class Post(models.Model):
    class Meta:
        verbose_name			= 'Post'
        verbose_name_plural		= 'Posts'
        ordering				= ['-id']

    post_title = models.CharField('제목', null=False, blank=False, max_length=100, help_text='제목 (100자 이내)')
    post_body = RichTextField('본문', null=False, blank=False, help_text='본문 입력')
    post_keywords = models.CharField('키워드', null=True, blank=True, max_length=100, 
										help_text='키워드 입력 (콤마로 구분), 내부 키워드 검색시 사용')
    post_publication = models.BooleanField('게시 여부', default=False, help_text='게시 활성 여부')
    post_registered_by = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='게시물 등록자',
										null=False, blank=False, on_delete=models.DO_NOTHING,default=4, help_text='게시물 등록자 선택',)
    post_thumbnail = models.ImageField('썸네일 이미지',null=True,blank=True, help_text='썸네일 이미지 등록') 
    post_preview = models.CharField('미리보기', null=False, blank=False, max_length=300, 
										help_text='게시물 미리보기 작성(최대 200자)')
    post_type = models.CharField('게시물 유형', null=False, blank=False, max_length=50,)
    post_exposed_date = models.DateField('게시일자', null=False, blank=False,)
    post_created_at = models.DateField('최초 생성일', null=True, blank=True, auto_now_add=True,)
    post_updated_at = models.DateField('최근 수정일', null=True, blank=True, auto_now=True,)
#    def save(self):
#        self.slug = slugify(self.post_title)
#        super(Post, self).save()

    def __str__(self):
        return self.post_title

#    def get_absolute_url(self):
#        return reverse('lead:post_detail', args=[self.pk])

class Scripting(models.Model):
    class Meta:
        verbose_name			= 'Script'
        verbose_name_plural		= 'Scripts'
        ordering				= ['-id']
	
    script_title = models.CharField('스크립트 이름', null=False, blank=False, max_length=50, 
										help_text='식별 가능한 스크립트 이름 입력(주석처리 후 소스에 삽입됩니다.)')
    script_body = models.TextField('스크립트', null=False, blank=False, 
									help_text=mark_safe("스크립트 입력 => 반드시 \'script\' 태그를 입력하십시오."),)
    script_expose = models.BooleanField('활성여부', null=False, blank=False, default=False, 
										help_text='KeepGrow 페이지 내 공통 스크립트 활성화 여부')
    script_created_at = models.DateField('최초 생성일', null=True, blank=True, auto_now_add=True,)
    script_updated_at = models.DateField('최근 수정일', null=True, blank=True, auto_now=True,)

    def __str__(self):
        return self.script_title

lead/forms.py
from django import forms
from .models import Lead

class LeadForm(forms.ModelForm):
    lead_company_corporation		= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"법인명"}))
    lead_company_name				= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"업체명"}))
    lead_company_website_url		= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"웹사이트"}))
    lead_contact_email				= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"이메일"}))
    lead_contact_department			= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"부서명"}))
    lead_contact_name				= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"이름"}))
    lead_contact_phone				= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"휴대전화"}))
    lead_contact_title				= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"직책"}))
    lead_event_inquiry				= forms.CharField(label='', widget=forms.Textarea(attrs={"placeholder":"상세 문의"}))
    lead_event_interests			= forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder":"관심 서비스"}))
    lead_marketing_agree			= forms.BooleanField(widget=forms.CheckboxInput, label='제품, 서비스 및 이벤트 관련 마케팅 정보를 수신하고 싶습니다.')
    lead_demo_request				= forms.BooleanField(widget=forms.CheckboxInput, label='데모를 요청합니다.')

    class Meta:
        model = Lead
        fields = ('lead_company_corporation','lead_company_name','lead_company_website_url',
                  'lead_contact_department','lead_contact_email','lead_contact_name',
                  'lead_contact_phone','lead_contact_title','lead_event_inquiry','lead_event_interests',
				  'lead_marketing_agree','lead_demo_request',
				  )

lead/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.db.models import Q

from .models import Lead, Post, Subscription
#from .forms import LeadForm

from django.views.generic import ListView, DetailView, CreateView


#Retrieve List
class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'lead/newsletter_list.html'
    paginate_by = 6

    def get_queryset(self, *args, **kwargs):
        qs = Post.objects.all()
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
					Q(post_title__icontains=query) | 
					Q(post_preview__icontains=query) |
					Q(post_body__icontains=query) | 
					Q(post_registered_by__username__icontains=query) |
					Q(post_keywords__icontains=query)
				)
        return qs


class PostDetailView(DetailView):
    template_name = 'lead/newsletter_detail.html'
	
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, pk=id_)

	
#class LeadCreateView(CreateView):
#    model = Lead
#    fields = ('lead_company_corporation','lead_company_name','lead_company_website_url',
#				'lead_contact_department','lead_contact_email','lead_contact_name',
#				'lead_contact_phone','lead_contact_title','lead_event_inquiry','lead_event_interests',
#				)
#    template_name = 'lead/lead_form.html'

# 반드시 수정하기!
#    success_url = reverse_lazy("lead:postlist")	

#    def get_success_url(self):
#        return reverse_lazy("lead:formsubmit", kwargs={"pk": int(self.object.pk)})


from django.shortcuts import render
from .forms import LeadForm

def leadcreate(request):
    form = LeadForm(request.POST or None)
        # form = LeadForm(request.POST)
    if form.is_valid():
        form = form.save(commit=False)
        form.lead_event_ipaddress = request.META['REMOTE_ADDR']
        form.lead_event_referrer = request.META['HTTP_REFERER']
        form.lead_event_user_agent = request.META['HTTP_USER_AGENT']
        form.lead_event_location = request.META['REQUEST_URI']
        form.save()

    context = {
			'form' : form
	}

    return render(request, 'lead/lead_form.html', context)


#index = ListView.as_view(model=Post, template_name='lead/posts.html')
#post_detail = DetailView.as_view(model=Post)


#CRUD SET

#post_new = CreateView.as_view(model=Post)

#post_edit = UpdateView.as_view(model=Post, fields='__all__')


#post_delete = DeleteView.as_view(model=Post, success_url=reverse_lazy('lead:index'))

#class PostDeleteView(DeleteView):
#    model = Post
#    success_url = reverse_lazy('lead:index')
#post_delete = PostDeleteView.as_view()

lead/templates/lead/lead_form.html
{% extends "base.html" %}
{% block title %}Form{% endblock title%}

{% block content %}

<form class='form' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">제출</button>
</form>


{% endblock content %}




<form method='POST'>{% csrf_token %}
	<input type='text' name='my_title' placeholder='your title'/>
	<input type='submit' value='save'/>
</form>





<form action='http://www.google.com/search' method='GET' target="_blank">
	<input type='text' name='q' placeholder='your search'/>
	<input type='submit' value='save'/>
</form>





<form method="POST">
	{% csrf_token %}
	{{ form.as_table }}
	<button type="submit">submit</button>
	<!--<input type='submit' value='Save'>-->
</form>

lead/templates/lead/newsletter_detail.html
{% extends "base.html" %}
{% block title %}Detail{% endblock title%}

{% block content %}

<a href="{% url 'lead:postlist' %}">뒤로가기</a>
<h1>{{ object.post_title }}</h1>
<p>{{ object.post_type }}</p>
By {{ object.post_registered_by }} | {{ object.post_created_at }}<br/><br/>
{{ object.post_body|safe }}<br /><br />



{% endblock content %}

lead/templates/lead/newsletter_list.html
{% extends "base.html" %}
{% block title %}List{% endblock title%}

{% load static %}
{% block content %}
{% include "lead/search_form.html" %}
{% spaceless %}
{% for object in object_list %}
	{% if object.post_publication == True %}

		{% if object.post_thumbnail %}
		<a href="{% url 'lead:postdetail' object.pk %}">
			<img src="{{ object.post_thumbnail.url }}" width="500px", height="500px"/>
		</a>
		{% endif %}<br/>
		<h1>{{ object.post_title|linebreaks }}</h1>
		{{ object.post_preview|linebreaks }}
		<p>{{ object.post_registered_by }} | {{ object.post_exposed_date }} 
		<!--<a href="{% url 'lead:postdetail' object.pk %}">View</a></p>-->
		<hr>
	<br/>
	<br/>
	{% endif %}
	
	{% empty %}
		{% if request.GET.q %}
			<p>일치하는 정보가 존재하지 않습니다.</p> 
		{% else %}
			<p>아무 게시물이 존재하지 않습니다.</p>
		{% endif %}

{% endfor %}
{% endspaceless %}

{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}
{% endblock content %}

lead/templates/lead/search_form.html
<form  method='GET' action='{% url "lead:postlist" %}'>
	<div class="form-group">
		<input type='text' name='q' placeholder="단어나 문장을 입력" value='{{ request.GET.q }}' />
	</div>
	<input  type='submit' value="검색" />	
</form>